### ISSUE TITLE
Transient Networking Errors & Timing Delay

### ISSUE THREAD

**Issue by mivinson** [astronomer/airflow-provider-fivetran-async#24]
Hello,

I am running into a failure in our production environment with the async sensor.  I have observed a few odd behaviors in this and I'm looking for direction on troubleshooting steps. Ultimately we were able to clear the task and it ran successfully.

1. Network issue:

```
[2023-05-12, 09:22:00 UTC] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/fivetran_provider_async/sensors.py", line 55, in execute_complete
    raise AirflowException(msg)
airflow.exceptions.AirflowException: error: Cannot connect to host api.fivetran.com:443 ssl:default [Connect call failed ('35.236.237.87', 443)]
```

```
[2023-05-12, 11:14:02 UTC] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/fivetran_provider_async/sensors.py", line 55, in execute_complete
    raise AirflowException(msg)
airflow.exceptions.AirflowException: error: API requests to Fivetran failed 3 times. Giving up.
```

It would appear that this is a networking issue that might have been caused by a service outage from Fivetran.  However, we were able to trigger the sync in an upstream task and the sync completed without error in Fivetran.  The Fivetran status page isn't showing any server issues on the day.  Any troubleshooting suggestions would be appreciated.

2. Timing Delay

We are observing large delays between the task initialization and the execution.  Any information you can provide about why we might be seeing these timing delays would be appreciated.  

Attempt 1: 1 hr 22 mintues
```
[2023-05-12, 08:00:16 UTC] {taskinstance.py:1465} INFO - Pausing task as DEFERRED. dag_id=marketing_app_data, task_id=sensor_fivetran_marketing_app, execution_date=20230511T080000, start_date=20230512T080016
[2023-05-12, 08:00:16 UTC] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-05-12, 08:00:16 UTC] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check

[2023-05-12, 09:22:00 UTC] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: marketing_app_data.sensor_fivetran_marketing_app scheduled__2023-05-11T08:00:00+00:00 [queued]>
```
Attempt 2: 1 hr

```
[2023-05-12, 09:23:01 UTC] {taskinstance.py:1465} INFO - Pausing task as DEFERRED. dag_id=marketing_app_data, task_id=sensor_fivetran_marketing_app, execution_date=20230511T080000, start_date=20230512T092301
[2023-05-12, 09:23:01 UTC] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-05-12, 09:23:01 UTC] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check

[2023-05-12, 10:22:40 UTC] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: marketing_app_data.sensor_fivetran_marketing_app scheduled__2023-05-11T08:00:00+00:00 [queued]>
[2023-05-12, 10:22:40 UTC] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: marketing_app_data.sensor_fivetran_marketing_app scheduled__2023-05-11T08:00:00+00:00 [queued]>
```

Attempt 3: 2 minutes

```
[2023-05-12, 10:23:42 UTC] {taskinstance.py:1465} INFO - Pausing task as DEFERRED. dag_id=marketing_app_data, task_id=sensor_fivetran_marketing_app, execution_date=20230511T080000, start_date=20230512T102342
[2023-05-12, 10:23:42 UTC] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-05-12, 10:23:42 UTC] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check

[2023-05-12, 10:25:49 UTC] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: marketing_app_data.sensor_fivetran_marketing_app scheduled__2023-05-11T08:00:00+00:00 [queued]>
[2023-05-12, 10:25:49 UTC] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: marketing_app_data.sensor_fivetran_marketing_app scheduled__2023-05-11T08:00:00+00:00 [queued]>
```

Attempt 4: 47 minutes
```
[2023-05-12, 10:26:51 UTC] {taskinstance.py:1465} INFO - Pausing task as DEFERRED. dag_id=marketing_app_data, task_id=sensor_fivetran_marketing_app, execution_date=20230511T080000, start_date=20230512T102650
[2023-05-12, 10:26:51 UTC] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-05-12, 10:26:51 UTC] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check

[2023-05-12, 11:14:01 UTC] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: marketing_app_data.sensor_fivetran_marketing_app scheduled__2023-05-11T08:00:00+00:00 [queued]>
[2023-05-12, 11:14:01 UTC] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: marketing_app_data.sensor_fivetran_marketing_app scheduled__2023-05-11T08:00:00+00:00 [queued]>
```

**Comment by sunank200** [comment]
@mivinson could you share the DAG as well, please? I am not able to replicate the above scenario mentioned.

**Comment by vatsrahul1001** [comment]
@mivinson can you kindly confirm if issue persists?
